version: 2

before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  binary: '{{ .ProjectName }}_v{{ .Version }}'
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64

archives:
- formats: [ 'zip' ]
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

changelog:
  disable: true

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
